[project]
name = "voice-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp-cors>=0.8.1",
    "edge-tts>=7.2.8",
    "faster-whisper>=1.2.1",
    "google-genai>=2.18.1",
    "groq>=1.6.0",
    "indic-transliteration>=2.3.82",
    "livekit-agents>=1.6.10",
    "livekit-plugins-fishaudio>=1.6.10",
    "python-dotenv>=1.2.3",
    "scipy>=1.17.1",
    "ten-vad>=1.0.6.8",
]
